# Generated by Django 5.2.8 on 2025-11-11 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ev_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='latitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='station',
            name='longitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
