# Generated by Django 5.2.8

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ev_app', '0004_add_booking_date_time_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='charging_progress',
            field=models.IntegerField(default=0),
        ),
    ]


