# Generated by Django 5.2.8 on 2025-11-12 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ev_app', '0005_alter_booking_date'),
        ('ev_app', '0005_booking_charging_progress'),
    ]

    operations = [
    ]
