# Generated by Django 5.2.8 on 2025-11-12 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ev_app', '0006_alter_booking_date_add_created_at'),
        ('ev_app', '0006_merge_20251112_1120'),
    ]

    operations = [
    ]
