# Generated by Django 5.2.8 on 2025-11-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ev_app', '0010_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
    ]
