# Generated by Django 5.2.8 on 2025-12-04 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ev_app', '0011_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
