# Generated by Django 5.2.8 on 2025-12-04 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ev_app', '0013_alter_booking_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='paid_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
