# Generated by Django 5.2.8 on 2025-12-08 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ev_app', '0015_vehicle_booking_vehicle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='vehicle_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='vehicle_number',
            new_name='number',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='battery_capacity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='connector_type',
            field=models.CharField(max_length=50),
        ),
    ]
